name: Android CI

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - closed

#  push:
#    branches: [ master ]


jobs:
  apk:
    name: Generate APK

    runs-on: ubuntu-latest

    steps:
      - name: Send APK to discord channel
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: './app/build/outputs/apk/debug/app-debug.apk'
