name: Android CI

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - closed

#  push:
#    branches: [ master ]


jobs:
  apk:
    name: Generate APK

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: send custom message with args
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          args: The ${{ github.event_name }} event triggered first step.

          
